"$schema" = 'https://starship.rs/config-schema.json'

format = '$all$line_break$jobs$time$status$os$shell$character '
right_format = '$docker_context$kubernetes$azure$aws$gcloud$battery'

add_newline = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[hostname]
disabled = false
ssh_only = false
format = '[$hostname]($style):'

[username]
disabled = false
show_always = true
format = '[$user]($style)@'

[directory]
disabled = false
truncate_to_repo = false

[package]
disabled = true

[container]
disabled = true

[shell]
disabled = false
zsh_indicator = ""
bash_indicator = "󱆃"
powershell_indicator = ""

[os]
disabled = false
format = "$symbol "
symbols.Ubuntu = ""
symbols.Windows = ""

[docker_context]
disabled = false
symbol = "󰡨 "
format = '$symbol[$context]($style) '
only_with_files = false

[kubernetes]
disabled = false
symbol = "󱃾 "
format = '$symbol[$context]($style) '

[azure]
disabled = false
symbol = " "
format = '$symbol[$subscription]($style) '

[aws]
disabled = false
symbol = "󰸏 "
format = '$symbol[($profile )\($region\)( \[$duration\])]($style) '

[gcloud]
disabled = false
symbol = "󰊭 "
format = '$symbol[$account]($style) '

[battery]
disabled = false
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "

[[battery.display]]
threshold = 20
style = "bold red"

[[battery.display]]
threshold = 40
style = "bold yellow"

[[battery.display]]
threshold = 100
style = "bold green"