"$schema" = 'https://starship.rs/config-schema.json'

format = '$all$line_break$jobs$battery$time$status$os$shell$character '
right_format = '$aws$gcloud$azure$kubernetes'

add_newline = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[hostname]
disabled = false
ssh_only = false
format = '[$hostname]($style):'

[username]
disabled = false
show_always = true
format = '[$user]($style)@'

[directory]
disabled = false
truncate_to_repo = false

[package]
disabled = true

[container]
disabled = true

[shell]
disabled = false
zsh_indicator = ""
bash_indicator = "󱆃"
powershell_indicator = ""

[os]
disabled = false
format = "$symbol "
symbols.Ubuntu = ""
symbols.Windows = ""

[kubernetes]
disabled = false
symbol = "󱃾 "
format = '$symbol[$context]($style) '

[azure]
disabled = false
symbol = " "
format = '$symbol[$subscription]($style) '

[aws]
disabled = false
symbol = "󰸏 "
format = '$symbol[($profile )\($region\)( \[$duration\])]($style) '

[gcloud]
disabled = false
symbol = "󰊭 "
format = '$symbol[$account]($style) '
